export type Product = { id?: number; slug: string; name: string; type: string; image: string; gallery: string[]; note: string; description: string; material: string; measures: string; care: string; availability: string; featured?: boolean };

export const fallbackProducts: Product[] = [
  { slug:'brincos-gota-rosa', name:'Brincos Gota Rosa', type:'Brincos', image:'/zibra-brincos-studio-v3.png', gallery:['/zibra-brincos-studio-v3.png','/zibra-brincos-studio-v2.png'], note:'Delicadeza que ilumina', description:'Brincos delicados em formato de gota, com pedras rosadas e contorno luminoso. Uma peça marcante na medida certa.', material:'Prata com acabamento polido e pedras de brilho rosado', measures:'Formato compacto · vendidos em par', care:'Evite contato com perfumes, cremes e água. Guarde na embalagem Zibra.', availability:'Disponível sob consulta', featured:true },
  { slug:'colar-fe', name:'Colar Fé', type:'Colar', image:'/zibra-colar-studio-v2.png', gallery:['/zibra-colar-studio-v2.png','/zibra-colar.jpeg'], note:'Um símbolo para levar consigo', description:'Um colar delicado que transforma fé em presença cotidiana, com pingente de cruz de desenho contemporâneo.', material:'Prata com acabamento polido', measures:'Corrente delicada · pingente retangular', care:'Limpe com flanela macia e guarde separado de outras peças.', availability:'Disponível sob consulta', featured:true },
  { slug:'corrente-grumet', name:'Corrente Grumet', type:'Corrente', image:'/zibra-corrente-grumet-studio.png', gallery:['/zibra-corrente-grumet-studio.png'], note:'Presença em cada elo', description:'Elos clássicos com acabamento preciso e brilho equilibrado para uma presença segura e versátil.', material:'Prata com acabamento espelhado', measures:'Espessura média · comprimento sob consulta', care:'Evite abrasivos e produtos químicos. Guarde seca.', availability:'Disponível sob consulta' },
  { slug:'corrente-trama', name:'Corrente Trama', type:'Corrente', image:'/zibra-corrente-trama-studio.png', gallery:['/zibra-corrente-trama-studio.png'], note:'Textura que captura a luz', description:'Uma trama refinada que acompanha o movimento e cria pontos sutis de luz sobre a pele.', material:'Prata com acabamento polido', measures:'Trama delicada · comprimento sob consulta', care:'Use flanela própria para prata e mantenha longe da umidade.', availability:'Disponível sob consulta' },
];

export function normalizeWordPressProduct(item: any): Product {
  const meta = item?.catalogo || item?.acf || item?.meta || {};
  const imageValue = meta.imagem_principal || item?._embedded?.['wp:featuredmedia']?.[0]?.source_url || '/zibra-brincos-studio-v3.png';
  const gallery = Array.isArray(meta.galeria) ? meta.galeria.map((entry:any)=>typeof entry === 'object' ? entry.url : entry) : typeof meta.galeria === 'string' ? meta.galeria.split(',').filter(Boolean) : [];
  const clean = (value:string='') => value.replace(/<[^>]+>/g, '');
  return { id:item.id, slug:item.slug || String(item.id), name:item.title?.rendered || meta.nome || 'Joia Zibra', type:meta.categoria || item?._embedded?.['wp:term']?.[0]?.[0]?.name || 'Joias', image:typeof imageValue === 'object' ? imageValue.url : imageValue, gallery:gallery.length ? gallery : [typeof imageValue === 'object' ? imageValue.url : imageValue], note:meta.descricao_curta || clean(item.excerpt?.rendered) || 'Elegância em cada detalhe', description:meta.descricao || clean(item.content?.rendered) || clean(item.excerpt?.rendered), material:meta.material || 'Informação sob consulta', measures:meta.medidas || 'Informação sob consulta', care:meta.cuidados || 'Guarde na embalagem Zibra e evite contato com produtos químicos.', availability:meta.disponibilidade || 'Disponível sob consulta', featured:Boolean(meta.destaque || item.sticky) };
}

export const whatsappUrl = (product?:string) => `https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || ''}?text=${encodeURIComponent(product ? `Olá! Gostaria de saber mais sobre ${product}.` : 'Olá! Gostaria de conhecer melhor a coleção Zibra.')}`;
